# profiles.yml file
dbttest:
  target: dev
  outputs:
    dev:
      type: databricks
      host: dbc-04415c5b-8769.cloud.databricks.com
      token: <token>
      http path: sql/protocolv1/o/2763539879433440/0323-075215-ywhjxljn
      port: 443
      dbname: main
      schema: dqlabs
      threads: 4