version: 2

models:
  - name: consolidate_vw.sql
    description: "merged view from DQ_QA_Module"
    columns:
      - name: property_id
        description: "Primary key"
        tests:
          - unique
          - not_null