version: 2

models:
  - name: consolidated_data_vw
    columns:
      - name: property_id
        tests:
          - unique:
              config:
                store_failures_as: ephemeral
          - not_null
  - name: financial_performance_data
    columns:
      - name: financing_details
        tests:
          - unique:
              config:
                fail_calc: "case when count(*) > 0 then sum(n_records) else 0 end"
                store_failures: true
                store_failures_as: ephemeral
          - not_null:
              config:
                store_failures: true
                error_if: ">100"
                warn_if: ">10"
                store_failures_as: ephemeral


